name: Build and Publish

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn

      - name: List test files
        run: ls -la src/__tests__

      - name: Testing the package
        run: yarn test --ci

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main

      - name: Building
        run: yarn build

      - name: Publishing to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
